apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql-container
    image: employees-mysql:1.0
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "admin"
    - name: MYSQL_DATABASE
      value: "employees"
