apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-app-replicaset
  namespace: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: web-app-container
        image: employees-web:1.0
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "localhost" # Still not fixed, but that's okay for this step
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "admin"
        - name: DBNAME
          value: "employees"
