apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  namespace: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: web-app-container
        image: employees-web:2.0
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql-service.mysql.svc.cluster.local" # Still not fixed, we will fix this in the next part!
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "admin"
        - name: DBNAME
          value: "employees"
