apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  namespace: web
  labels:
    app: employees
spec:
  containers:
  - name: web-app-container
    image: employees-web:1.0
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      # NOTE: This value is temporary and will not work yet.
      # We will fix this when we introduce Services.
      value: "localhost"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "admin"
    - name: DBNAME
      value: "employees"
